twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  welcome-message: Hello SS
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000

  retry-config:
    initial-interval-ms: 1000
    max-interval-ms: 10000
    multiplier: 2.0
    maxAttempts: 3
    sleep-time-ms: 2000
